### PR TITLE
fix(Connection): send hostname in ping

### LINKED ISSUE #64: PING should match more closely to TMI
**Describe the bug**
fdgt sends `PING`
TMI sends `PING :tmi.twitch.tv`
Some libraries do not expect this difference

**To Reproduce**
1. Connect to the websocket
2. Wait for a PING
3. Notice discrepancy

**Expected behavior**
fdgt should send `PING :tmi.twitch.tv`

**Additional context**
TMI Reference: https://dev.twitch.tv/docs/irc/guide
Responsible code: https://github.com/fdgt-apis/api/blob/22342f110752b45e710ab6cee6b63f397aba407a/src/structures/Connection.js#L187

### PR DESCRIPTION
**Pull request by iProdigy**
Resolves #64. Thanks to @Mrbysco for their help in identification of the bug.

### CODE REVIEW

**Comment by trezy** [comment]
@iProdigy Could you rebase this on `main`? I just pushed a fix for the tests not being run.

File: src/structures/Connection.js [hunk 1]
```diff
@@ -184,7 +184,7 @@ export default class extends EventEmitter {
 				connectionID: this.id,
 			}, 'info')
 
-			this.send('PING')
+			this.send('PING :tmi.twitch.tv')
```
Comment (trezy) [inline src/structures/Connection.js:187]: Instead of hardcoding the host, let's use the `HOST` variable (it's deconstructed from `process.env` on line 32).
